name: Push pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -la
          ACCOUNT="540173290202"
          echo "AMI=`cat ami.txt`" >> $GITHUB_ENV
          echo "Sharing ${{ env.AMI }} with account $ACCOUNT"
          aws ec2 modify-image-attribute --image-id ${{ env.AMI }} --launch-permission "{\"Add\":[{\"UserId\":\"$ACCOUNT\"}]}"
      - run: |
          STACK_NAME="gateway-evry-vpn-proxy-1"
          IP="108.128.88.8"
          SQS_URL="https://sqs.eu-west-1.amazonaws.com/540173290202/reepay-evry-updater-sqs.fifo"
          MESSAGE="{\"stack_name\" : \"$STACK_NAME\",\"ami\" :\"${{ env.AMI }}\",\"ip\" :\"$IP\"}"
          echo "Sending message $MESSAGE to $SQS_URL"
      - run: |
          STACK_NAME="gateway-evry-vpn-proxy-2"
          IP="108.128.88.9"
          SQS_URL="https://sqs.eu-west-1.amazonaws.com/540173290202/reepay-evry-updater-sqs.fifo"
          MESSAGE="{\"stack_name\" : \"$STACK_NAME\",\"ami\" :\"${{ env.AMI }}\",\"ip\" :\"$IP\"}"
          echo "Sending message $MESSAGE to $SQS_URL"

  deploy-to-pci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -al
          ACCOUNT="763104487069"
          echo "AMI=`cat ami.txt`" >> $GITHUB_ENV
          echo "Sharing ${{ env.AMI }} with account $ACCOUNT"
      - run: |

          echo "Deploy to PCI by sending these messages to https://sqs.eu-west-1.amazonaws.com/763104487069/reepay-evry-updater-sqs.fifo:"
          echo "{\"stack_name\": \"gateway-evry-vpn-proxy-1\", \"ami\": \"${{ env.AMI }}\", \"ip\": \"108.128.88.8\"}"
          echo "{\"stack_name\": \"gateway-evry-vpn-proxy-2\", \"ami\": \"${{ env.AMI }}\", \"ip\": \"108.128.88.9\"}"